name: New Release
on:
  issues:
    types: [opened]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'microsoft/vscode-github-triage-actions'
          ref: master
      - name: Install Actions
        run: npm install --production
      - name: Run New Release
        uses: ./new-release
        with:
          token: ${{secrets.VSCODE_ISSUE_TRIAGE_BOT_PAT}}
          appInsightsKey: ${{secrets.TRIAGE_ACTIONS_APP_INSIGHTS}}
          label: new release
          labelColor: "006b75"
          labelDescription: Issues found in a recent release of VS Code
          days: 1
