name: Test blob@12.1.1
on:
  issue_comment:
    types: [created]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'microsoft/vscode-github-triage-actions'
          ref: master
      - name: Install Actions
        run: npm install --production
      - name: Install Blob Stuff
        run: npm install @azure/core-http@1.1.7 @azure/storage-blob@12.1.1
      - name: Run Test blob
        uses: ./blob-storage-test
        with:
          appInsightsKey: ${{secrets.TRIAGE_ACTIONS_APP_INSIGHTS}}
          token: ${{secrets.VSCODE_ISSUE_TRIAGE_BOT_PAT}}
          storageKey: ${{secrets.AZURE_BLOB_STORAGE_CONNECTION_STRING}}]
