name: Test Plan Item Validator
on:
  issues:
    types: [edited, labeled]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'microsoft/vscode-github-triage-actions'
          ref: master
      - name: Install Actions
        run: npm install --production
      - name: Run Test Plan Item Validator
        uses: ./test-plan-item-validator
        with:
          appInsightsKey: ${{secrets.TRIAGE_ACTIONS_APP_INSIGHTS}}
          token: ${{secrets.VSCODE_ISSUE_TRIAGE_BOT_PAT}}
          label: test plan item
          invalidLabel: invalid-tpi
          comment: this test plan item is trash
