name: Classifier
on:
  schedule:
    - cron: 0,30 * * * *
  repository_dispatch:

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'microsoft/vscode-github-triage-actions'
          ref: master
          lfs: true
          path: ./actions
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: "Run Classifier: Scraper"
        uses: ./actions/classifier/fetch-issues
        with:
          # slightly overlapping to protect against issues slipping through the cracks if a run is delayed
          from: 360
          until: 5
      - name: Set up Python 3.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.7
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install --upgrade numpy scipy scikit-learn joblib nltk
      - name: "Run Classifier: Generator"
        run: python ./actions/classifier/generate-labels/main.py
      - name: "Run Classifier: Labeler"
        uses: ./actions/classifier/apply-labels
        with:
          config-path: classifier
          __createLabels: yep