name: Echoer
on:
  issue_comment:
    types: [created]
  issues:
    types: [opened, edited, labeled, milestoned]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'microsoft/vscode-github-triage-actions'
          ref: master
      - name: Install Actions
        run: npm install --production
      - name: Run Echoer
        uses: ./echoer
