name: Locker
on:
  repository_dispatch:
    types: [trigger-locker]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: "microsoft/vscode-github-triage-actions"
          path: ./actions
          ref: v41
      - name: Install Actions
        run: npm install --production --prefix ./actions
      - name: Run Locker
        uses: ./actions/locker
        with:
          daysSinceClose: 0.0007
          appInsightsKey: ${{secrets.TRIAGE_ACTIONS_APP_INSIGHTS}}
          daysSinceUpdate: 0.0007
          ignoredLabel: "*out-of-scope"
          ignoreLabelUntil: "author-verification-requested"
          labelUntil: "verified"
