name: Locker
on:
  schedule:
    -cron: 0/5 * * * *

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'JacksonKearl/vscode-triage-github-actions'
          ref: master
      - name: Run Locker
        uses: ./locker
        with:
          token: ${{secrets.VSCODE_ISSUE_TRIAGE_BOT_PAT}}
          daysAfterClose: 0.0007
          daysSinceLastUpdate: 0.0007
          ignoredLabel: ignore
