name: Needs More Info Closer
on:
  repository_dispatch:
  issues:
    types: ['pinned']
  schedule:
    - cron: 30 * * * *

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'JacksonKearl/vscode-triage-github-actions'
          ref: master
      - name: Run Needs More Info Closer
        uses: ./needs-more-info-closer
        with:
          label: needs more info
          closeDays: 0.0007
          closeComment: too little info bye
          pingDays: 0.0070
          pingComment: ${asignee} plz c ${author}'s comment k thx bie
