name: Queryer
on: repository_dispatch
#   issue_comment:
#     types: [created]

jobs:
  main:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v2
        with:
          repository: 'microsoft/vscode-github-triage-actions'
          ref: master
      - name: Install Actions
        run: npm install --production
      - name: Run Queryer
        uses: ./queryer
